---
title: "Wildfire Disasters Lite Summary Report"
format: html
editor: visual
---

```{r}
#| include: true
library(tidyverse)
library(targets)
library(gt)
library(sf)
output_file <- tar_read(output_file)
data <- tar_read(pop_density)
head(data)
```

*Last run: `r today()`*

Output File Details:

`r output_file`

-   File Size: `r as.character(fs::file_info(path = output_file)$size)`
-   File Checksum (md5): `r tools::md5sum(output_file)`

```{r}
row_counts <- tribble(
	~data_set, ~nobs_wflite, ~nobs_wfheavy,
	'event_fema'    , nrow(tar_read(event_fema)),     1339,
	'event_ics209'  , nrow(tar_read(event_ics209)),  32425,
	'event_redbook' , nrow(tar_read(event_redbook)),  1126,
	'event'         , nrow(tar_read(event)),         32512, 
	'spatial_fired' , nrow(tar_read(spatial_fired)), 98723,
	'spatial_mtbs'  , nrow(tar_read(spatial_mtbs)),  20644,
	'spatial_nifc'  , nrow(tar_read(spatial_nifc)),  54158,
	'spatial'       , nrow(tar_read(spatial)),        5461
)

row_counts
```

Burn Perimeter Join Types

```{r}
tar_read(spatial) %>%
	st_drop_geometry() %>% 
	group_by(geometry_method) %>%
	summarize(n_wflite = n())
```

## Documentation

See detailed documentation for the input and output data sets here: <https://lpiep.github.io/wildfire_disasters_lite/>
