site_name: Wildfire Disaster Dataset Harmonization
nav:  
  - Home: index.md
  - Process Flow: wildfire_disasters_lite_diagram.png
  - Raw Data Descriptions:
    - NIFC: raw_data_desc/nifc.md
    - FEMA: raw_data_desc/fema.md
    - MTBS: raw_data_desc/mtbs.md
    - FIRED: raw_data_desc/fired.md
    - ICS209: raw_data_desc/ics209.md
    - WUI: raw_data_desc/wui.md
    - Red Book: raw_data_desc/redbook.md
    - GHS Population: raw_data_desc/ghs.md
theme:
  name: material