---
title: "Manuscript Validation"
format: pdf
execute-dir: file
fig-width: 8
fig-height: 5
execute: 
  echo: false
  warning: false
---

```{r setup}
#| include: false
#| 
library(sf)
library(arrow)
library(tidyverse)
library(patchwork)
library(gguw)
library(showtext)
showtext_auto()
font_add("Arial", regular = "arial.ttf") 

theme_set(
  theme_uw() +
  theme(
    plot.title = element_blank(),#element_text(size = 18, hjust = 0.5),
    axis.line = element_line(linewidth = .1),
    axis.ticks = element_line(), 
    text = element_text(family = 'Arial'), 
    axis.title.x = element_blank(),
  )
)
pal <- c('WFBZ Disaster' = '#AB3329', 'ICS-209-PLUS' = '#EBAA6C')
```

## Comparison Data Sets

ICS-209-PLUS https://github.com/katiemcconnell/ICS-209-PLUS_spatiotemporal_linkage
<!--
FRESC https://www.sciencebase.gov/catalog/item/61707c2ad34ea36449a6b066 (metadata: https://www.sciencebase.gov/catalog/file/get/61aa537dd34eb622f699df81?f=__disk__d0%2F63%2F53%2Fd063532049be8e1bc83d1d3047b4df1a5cb56f15&transform=1&allowOpen=true)
--> 

```{r data}
ours <- read_sf('../wfbz.geojson') #%>% filter(wildfire_year <= 2020)
ics209plus <- read_parquet('../data/reference/ICS-209-PLUS_spatiotemporal_linkage_county.parquet')
#fresc <- st_read(dsn = '../data/reference/Fire_Feature_Data_Pro2_8_Geodatabase/Fire_Feature_Data.gdb/', query = 'select * from USGS_Wildland_Fire_Combined_Dataset where Fire_Year >= 1999 and Assigned_Fire_Type not like \'%Prescribed%\'')
compare <- bind_rows(
    ours %>% 
        st_drop_geometry() %>% 
        group_by(Year = wildfire_year) %>% 
        summarize(
            `Wildfire burn zone disasters, N` = n(),
            `Civilian fatalities, N` = sum(wildfire_max_civil_fatalities, na.rm = TRUE),
            `Structures destroyed, N` = sum(wildfire_struct_destroyed, na.rm = TRUE),
            `Total fatalities, N` = sum(wildfire_total_fatalities, na.rm = TRUE)
        ) %>% 
         mutate(Dataset = 'WFBZ Disaster'),
    ics209plus %>%
        group_by(INCIDENT_ID) %>%
        slice_head(n = 1) %>% # just take one of the counties
        mutate(
          disaster = (STR_DESTROYED_TOTAL > 0) | ((YEAR > 2013) & FATALITIES_PUBLIC > 0) |  ((YEAR <= 2013) & FATALITIES > 0)
        ) %>%
        group_by(Year = YEAR) %>% 
        summarize(
            `Wildfire burn zone disasters, N` = sum(disaster, na.rm = TRUE),
            `Civilian fatalities, N` = sum(FATALITIES_PUBLIC, na.rm = TRUE),
            `Total fatalities, N` = sum(FATALITIES, na.rm = TRUE),
            `Structures destroyed, N` = sum(STR_DESTROYED_TOTAL, na.rm = TRUE)
        ) %>%
        mutate(Dataset = 'ICS-209-PLUS') 
)

```

## Comparison Figures

### Number of Disaster Fires

For ICS209-PLUS, we defined a disaster fire as a fire that destroyed a building, had any fatality in or before 2013, or had a civilian fatality after 2013. 

```{r}
ggplot(compare) + 
  geom_line(aes(x = Year, y = `Wildfire burn zone disasters, N`, color = Dataset)) +
	scale_color_manual(values = pal)
```

### Fatalities

```{r}
#| fig-height: 8
p1 <- ggplot() + 
  geom_line(data = compare, aes(x = Year, y = `Civilian fatalities, N`, color = Dataset)) +
  annotate('segment', x = 2013.5, xend = 2013.5, y = 0, yend = 50, linetype = 'dashed') +
  annotate('text', x = 2013.5, y = 55, label = 'ICS-209 begins reporting\ncivilian fatalities separately.', size = 3, angle = -55, hjust = 1) + 
	scale_color_manual(values = pal)

p2 <- ggplot() + 
  geom_line(data = compare, aes(x = Year, y = `Total fatalities, N`, color = Dataset)) +
	scale_color_manual(values = pal)

p1 + p2 + plot_layout(ncol = 1)
```

### Structures

```{r}
ggplot(compare) + 
  geom_line(aes(x = Year, y = `Structures destroyed, N`, color = Dataset)) +	
	scale_color_manual(values = pal) + 
	scale_y_continuous(labels = scales::comma)

```
