name: Check pipeline freshness

on:
  pull_request:

jobs:
  check-pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master

      - name: Install Linux system dependencies
        run: |
          sudo apt-get install libcurl4-openssl-dev
          sudo apt-get install libssl-dev
          sudo apt-get install libzmq3-dev

      - name: Cache packages
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: ${{ runner.os }}-renv-

      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()
          
      - name: Check for outdated targets
        run: |
          Rscript -e '
            out <- targets::tar_outdated()
            if (length(out) > 0) {
              message("❌ Pipeline is not up to date. Run `targets::tar_make()` to update it."))
              quit(status = 1)
            } else {
              message("✅ Pipeline is up-to-date.")
            }
          '
