name: Check pipeline freshness

on:
  pull_request:

jobs:
  check-pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Cache renv library
        uses: actions/cache@v4
        with:
          path: renv/library
          key: renv-${{ runner.os }}-${{ hashFiles('renv.lock') }}
          restore-keys: |
            renv-${{ runner.os }}-

      - name: Restore renv
        run: Rscript -e 'if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv"); renv::restore()'

      - name: Check for outdated targets
        run: |
          Rscript -e '
            out <- targets::tar_outdated()
            if (length(out) > 0) {
              message("❌ Pipeline is not up to date. Run `targets::tar_make()` to update it."))
              quit(status = 1)
            } else {
              message("✅ Pipeline is up-to-date.")
            }
          '
